### ISSUE TITLE
Post-reorder static UIImage covers cell animation

### ISSUE THREAD

**Issue by bobsmells** [hpique/HPReorderTableView#1]
This works well - nicely done!  The only issue I'm having is that before the reorder, my cells have an animation going, on endless loop.  I don't mind the fact that while dragging, the content is replaced by a static screenshot UIImage of the cell (that actually feels intuitive for the user) but after the drop in the new location, the static screenshot is over the top of my actual cell and hence I can't see the animation.  Am I doing something wrong or is there some way to remove the static image after the reorder?

**Comment by hpique** [comment]
Thanks @bobsmells! Yes, the static image should be removed. I'll give it a look shortly.

**Comment by hpique** [comment]
I'm not seeing this behavior. Here's a quick test I did by adding an activity indicator to the cells of the demo project:

![animation test](https://cloud.githubusercontent.com/assets/912531/2698756/46324ee6-c3fe-11e3-82e3-771243ef5822.gif)

Can you provide a sample project with the problem?

**Comment by bobsmells** [comment]
Hmmm that's interesting.  I'll see if I can think about a cut down sample.
My current project has the cell.contentView do a "wiggle" animation like
the movement you get when you hold down an icon on the iPhone home screen
(to delete or move apps). It looks like the animation can't be seen due to
the front image overlaying it - I inspected it with Spark Inspector and
it's definitely in front of it, although that's no guarantee that this is
the problem.  Is there any reason you can think of that the movement of the
custom cell would cancel a CAAnimation? My own cancel method certainly
never gets called.

**Comment by bobsmells** [comment]
Hey Hermes, I ended up solving this.  You're right, it does remove the snapshot view after the drag - I think Spark Inspector is somehow holding onto a cached view of the UIView hierarchy, even if I refresh it.  Anyway, the problem seems to be that once the animation for the reorder kicks off, my own animation of the cell's contentView seems to be cancelled.  I'm not sure why because they're not the same view being animated.  But basically I added a line in the completion block of your reorder animation to restart my own.  e.g. the didEndLongPressGestureRecognizer method is now:
- (void)didEndLongPressGestureRecognizer:(UILongPressGestureRecognizer*)gestureRecognizer
  {
  if (!_reorderCurrentIndexPath)
  {
      HPGestureRecognizerCancel(gestureRecognizer);
      return;
  }
  
  NSIndexPath *indexPath = _reorderCurrentIndexPath;
  
  { // Reset
      [_scrollDisplayLink invalidate];
      _scrollDisplayLink = nil;
      _scrollRate = 0;
      _reorderCurrentIndexPath = nil;
      _reorderInitialIndexPath = nil;
  }
  
  [self animateShadowOpacityFromValue:_reorderDragView.layer.shadowOpacity toValue:0];
  
  [UIView animateWithDuration:HPReorderTableViewAnimationDuration
                   animations:^{
                       CGRect rect = [self rectForRowAtIndexPath:indexPath];
                       _reorderDragView.frame = CGRectOffset(_reorderDragView.bounds, rect.origin.x, rect.origin.y);
                   } completion:^(BOOL finished) {
                       [self reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];
                       [self performSelector:@selector(removeReorderDragView) withObject:nil afterDelay:0]; // Prevent flicker
                       [[self cellForRowAtIndexPath:indexPath].contentView wiggle];
                   }];
  }

Thanks for your help, and for the great component.  I'll be sure to credit you in this next release of my app.

**Comment by hpique** [comment]
Thanks for the update @bobsmells.

Interesting. Maybe a `tableView:didFinishReorderingCellAtIndex:` (or similar) delegate method would prevent you from having to modify the code. I'll keep in it mind for future updates.

**Comment by bobsmells** [comment]
Yeah that's a good idea, there are probably other events that people might
want to happen at that point.
