### ISSUE TITLE
The animation differs after long pressing each cell

### ISSUE THREAD

**Issue by umekun123** [hpique/HPReorderTableView#10]
Hi, thanks for the nice library.

However, the pop up animation differs every time I long press each tableview cell, sometimes it pops to the upper side, sometimes it pops to the below.

Is there any way to show only one pop animation after long pressing?

**Comment by hpique** [comment]
Hi @umekun123. IIRC, it depends on where you tap the cell. The behavior should be consistent, not random.

Changing the code to always move the cell to a certain y distance should be very simple. It's this line: https://github.com/hpique/HPReorderTableView/blob/master/HPReorderTableView/HPReorderTableView.m#L249

**Comment by umekun123** [comment]
Great, I thought it was a bug, thanks for your quick reply!
