### ISSUE TITLE
UITableViewController?

### ISSUE THREAD

**Issue by Sun3** [hpique/HPReorderTableView#2]
Is there a way to use this control with a UITableViewController instead?

Thank you.

**Comment by hpique** [comment]
You might be able to trick a `UITableViewController` into using `HPReorderTableView` by setting the class of the main view in Interface Builder. Haven't tried it myself. Let me know if it works.

**Comment by Sun3** [comment]
So far its working pretty good. Just a little show when dragging to hidden rows, the scrolling is slow. It might be because in my - (void)tableView:(UITableView *)tableView moveRowAtIndexPath:(NSIndexPath *)sourceIndexPath toIndexPath:(NSIndexPath *)destinationIndexPath   I am saving the Core Data reorder cells. Perhaps there is a better place to do this only once for Core Data UITableViews?

I had to remove form below procedure the [tableView begingUpdates] and [tableview endUpdates] before it was crashing on the endUpdates while dragging.
- (void)reorderCurrentRowToIndexPath:(NSIndexPath*)toIndexPath

Thank you for the suggestion.

**Comment by hpique** [comment]
You're welcome @Sun3 .

`tableView:moveRowAtIndexPath:` runs in the UI thread so whatever you do there should be brief. If saving the model is expensive, you could save after a delay, only the last time (`performSelector:` and `cancelPreviousPerformRequestsWithTarget:selector:object:` might help).

**Comment by Sun3** [comment]
The `performSelector:` with the `cancelPreviousPerformRequestsWithTarget:selector:object:` worked perfectly and now it is saving only once because I am using a delay.

Thank you @hpique you have a great control.
