### ISSUE TITLE
cellForRowAtIndexPath custom cell with Images issue

### ISSUE THREAD

**Issue by Sun3** [hpique/HPReorderTableView#3]
I am running into an issue in the cellForRowAtIndexPath while dragging the row around eventually it crashes on the line below. Any thoughts?

Note: Since images are stored as external files in Core Data sometimes they take a few seconds to load. In order not to bug down the system I am using the dispatch_async. If I do not use the dispatch_async it does not crash

Crashes

```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
        ....
        cell.imageViewPhoto.image = nil;
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
            NSArray *listImagesArray = list.relationship_List_Images.allObjects;
            NSArray *imagesNamesArray = [listImagesArray valueForKey:@"image"];

            UIImage* thumbnail = [[UIImage imageWithData:[imagesNamesArray objectAtIndex:0]] fixToCorrectOrientation:160 compressionQuality:1.0]; //[UIImage imageWithData:[imagesNamesArray objectAtIndex:0]];
            if (thumbnail) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    //return to the main thread to update the UI
                    if ([[self.tableView indexPathsForVisibleRows] containsObject:indexPath]) {
                        //check that the relevant data is still required
                        MasterViewControllerCell * correctCell = (MasterViewControllerCell *)[self.tableView cellForRowAtIndexPath:indexPath];
                        //get the correct cell (it might have changed)
                        correctCell.imageViewPhoto.image = thumbnail; // CRASHES HERE
                    }
                });
            }
            cell.imageViewPhoto.hidden = NO;
        });
       ....
```

Does not crash

```
        NSArray *listImagesArray = list.relationship_List_Images.allObjects;
        NSArray *imagesNamesArray = [listImagesArray valueForKey:@"image"];
        cell.imageViewPhoto.image =  [[UIImage imageWithData:[imagesNamesArray objectAtIndex:0]] fixToCorrectOrientation:160 compressionQuality:1.0]; //[UIImage imageWithData:[imagesNamesArray objectAtIndex:0]];
        cell.imageViewPhoto.hidden = NO;
        cell.labelNoteRightMarginContraint.constant = 100;
```

Thank you.

**Comment by hpique** [comment]
Where exactly does it crash and what's the error message?

**Comment by Sun3** [comment]
It crashes on the below line when it is trying to assign the image to the imageView control in the cell.

```
correctCell.imageViewPhoto.image = thumbnail; // CRASHES HERE
```

Error:

-[UITableViewCell imageViewPhoto]: unrecognized selector sent to instance 0x12f689470

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITableViewCell imageViewPhoto]: unrecognized selector sent to instance 0x12f689470'

**Comment by hpique** [comment]
The problem might be that your async code is trying to set properties on the empty cell, which is not necessarily of your type `MasterViewControllerCell`. 3 options:
- Don't ask for the cell again and use the original cell variable.
- Check the type of the cell returned by `cellForRowAtIndexPath:` before doing anything.
- Use `registerTemporaryEmptyCellClass:` to register you cell class.

**Comment by Sun3** [comment]
@hpique Thank you for the suggestions I ended up using Option 2

```
//get the correct cell (it might have changed)
if ([correctCell isKindOfClass:[MasterViewControllerCell class]]) {
     correctCell.imageViewPhoto.image = thumbnail;
}
```
